// +build !integration

package s3out

import (
	"time"

	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/stretchr/testify/mock"
)

type s3Mock struct {
	mock.Mock
}

func (s *s3Mock) PutObject(obj *s3.PutObjectInput) (*s3.PutObjectOutput, error) {
	s.Called(obj)
	return new(s3.PutObjectOutput), nil
}

// consumerMock is an autogenerated mock type for the ConsumerAPI type
type consumerMock struct {
	mock.Mock
}

// AppendLine provides a mock function with given fields: _a0
func (_m *consumerMock) AppendLine(_a0 string) {
	_m.Called(_a0)
}

// Run provides a mock function with given fields:
func (_m *consumerMock) Run() {
	_m.Called()
}

// Shutdown provides a mock function with given fields:
func (_m *consumerMock) Shutdown() {
	_m.Called()
}

// Tick provides a mock function with given fields: _a0
func (_m *consumerMock) Tick(_a0 time.Time) {
	_m.Called(_a0)
}
